### ISSUE TITLE
ClayModal blinks when hovering an element with ClayTooltip on IE11

### ISSUE THREAD

**Issue by naraandrade** [liferay/clay#3675] opened 2020-08-31 18:18 UTC
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?
I've made an [example](https://codesandbox.io/s/musing-fire-fg4um?fontsize=14&hidenavigation=1&theme=dark), but it wasn't possible to test it on IE11 because the page of codesanbox doesn't load on this browser. I'm not sure if this example reproduces the problem.

## What are the steps to reproduce?
The steps to reproduce the bug can be found in this [ticket](https://issues.liferay.com/browse/LPS-119758).

## What is the expected result?
The ClayModal shouldn't be blinking.

## Environment

| Tech  | Version |
| ----- | ------- |
| ClayModal  | v3.7.2  |
| ClayTooltip  | v3.3.5  |
| React |     v16.12.0    |

**Comment by matuzalemsteles** [comment] 2020-09-21 22:12
Hey @naraandrade apparently doesn't seem like a problem with Clay, I modified the demo to get closer to the codesandbox example in the Storybook but I couldn't reproduce it.

Win 10
![Kapture 2020-09-21 at 19 08 27](https://user-images.githubusercontent.com/13750819/93826700-34aac480-fc3e-11ea-8f24-a3c9d768bcb6.gif)

**Comment by naraandrade** [comment] 2020-09-23 17:44
Thanks, @matuzalemsteles. I'll continue to investigate the problem... We are using the same component structure on another page that works fine on IE11, the only difference is that it's not wrapped by a modal. If you have any suggestions, I would appreciate if you share it. Thanks again :)

**Comment by matuzalemsteles** [comment] 2020-09-23 19:44
> Thanks, @matuzalemsteles. I'll continue to investigate the problem... We are using the same component structure on another page that works fine on IE11, the only difference is that it's not wrapped by a modal. If you have any suggestions, I would appreciate if you share it. Thanks again :)

@naraandrade I did some tests to try to reproduce this but was unable to get to the modal blink, an assumption would be to investigate if it is causing some type of extra rendering in Modal or who controls it or this blink might be related to some CSS.

**Comment by naraandrade** [comment] 2020-10-02 20:25
@matuzalemsteles Apparently, it's an issue with the "center" prop passed to the ClayModal. When I removed it, the modal stopped to blink.

**Comment by matuzalemsteles** [comment] 2020-10-02 22:22
@naraandrade I'm going to take a look at this again on Monday, thanks for bringing this.

**Comment by matuzalemsteles** [comment] 2020-10-05 18:40
Hey @naraandrade, I still can't reproduce inside the Storybook using the `center` property enabled but I can reproduce only within the DXP, in the case of the ticket. Apparently, it could be a problem with repaint that is taking too long and causing the blink. I'm not sure why this happens only with the `center` I will try to continue investigating because it only happens in DXP. @pat270 could you take a look at this when you have time? I'm unable to collect much but if you provide anything information would be very welcome.

**Comment by matuzalemsteles** [comment] 2022-09-05 20:14
I'm closing this, this seems to be something very unique to IE11 and is something that is no longer worth fixing since we no longer support IE11.

**Closed by matuzalemsteles** 2022-09-05 20:14 UTC
Labels: type: bug, comp: clay-components, 3.x
