### ISSUE TITLE
Lexicon: Ascend and Descend buttons in Management Bar not visible on Mobile or minimized browsers

### ISSUE THREAD

**Issue by fortunatomaldonado** [liferay/clay#1252] opened 2018-10-22 18:38 UTC
When using Liferay on a mobile device/smaller browser size, you do not have the ability to sort content due to the ascending and descending arrows missing from the UI. This can be reproduced in all instances of management bar.

Steps to reproduce:
1. Go to Web Content and add a folder and give it a name
2. Look at the management bar an notice you are able to sort content with asc/desc buttons.
3. Shrink browser size or visit Liferay instance on mobile

**Comment by blzaugg** [comment] 2018-10-27 01:37
https://issues.liferay.com/browse/LPP-31606?focusedCommentId=1609567&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1609567

**Comment by pat270** [comment] 2018-10-30 23:08
This is fixed in Lexicon CSS 1.0.29.

**Closed by pat270** 2018-10-30 23:08 UTC
Labels: 1.x

**Comment by duracell80** [comment] 2018-12-03 19:42
Can anyone offer any breadcrumbs of explanation of why Lexicon issues are being reported in Clay and why Lexicon CSS site isn't being updated? And because this affects _unstyled / _styled in DXP 7.0 we as theme maintainers need WAY more details and help in what version information and NPM activity we need to conduct to keep pace with Liferay themes.

**Comment by pat270** [comment] 2018-12-03 19:54
@duracell80 Sorry about the site not being updated, we'll get this updated soon. I filed an issue at https://github.com/liferay/clay/issues/1342.

Lexicon CSS is under https://github.com/liferay/clay/tree/1.x which is why issues are being reported in this repo.

For the documentation site not being updated, https://github.com/jbalsas/lexiconcss/pulls.

In the mean time, changes for 1.0.27, 1.0.28, and 1.0.29 can be found at https://github.com/liferay/clay/blob/1.x/CHANGELOG.md.

/cc @jbalsas

**Comment by duracell80** [comment] 2018-12-03 20:48
Wow that really is confusing. I'm being told by support that this PR resolves an animation issue. Additionally I'm seeing animations in IE11 crash the browser when mousing out of a web content title field into a different field. 100% CPU usage, causing users in IE to not be able to even write web content due to this UI performance issue.

Currently I have no real grounding on how to proceed and can't trace a clear path given the information I was directed to.

**Comment by pat270** [comment] 2018-12-03 22:14
The changes in this pull were only to allow the sort arrow buttons to be aligned on the same line as Order by: {property} in smaller screens. The `hidden-xs` class should have been removed in the markup for 7.0. If it's still there it's a regression and needs to be fixed.

https://github.com/liferay/clay/issues/1266 only fixes an animation issue with the Product Menu and other slide out navigations in IE11 and isn't related to the editable title element in web content.
