### ISSUE TITLE
Forward References of ClayLink

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#2280] opened 2019-08-15 22:16 UTC
Some Routing libraries like `next/link` doesn't allow pass `ClayLink` due to a missing reference for it.

/cc @ygorcosta @matuzalemsteles

**Comment by bryceosterhaus** [comment] 2019-08-15 22:41
Duplicate of https://github.com/liferay/clay/issues/2250 ? also PR just sent upstream for this, let me know if I am missing something.

**Comment by matuzalemsteles** [comment] 2019-08-20 21:11
Fixed #2281

**Closed by matuzalemsteles** 2019-08-20 21:11 UTC
Labels: 3.x, comp: clay-components, type: enhancement
