### ISSUE TITLE
Right Nav Bar does not stick to the top on IE

### ISSUE THREAD

**Issue by Adriverforlife** [liferay/clay#2791] opened 2019-12-12 19:43 UTC
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?
Go to the Docs for Clay v3.0 with Internet Explorer and you can see that the Navigation Bar on the right. Scroll down and it will scroll away with the rest of the content. 
![Search](https://user-images.githubusercontent.com/50709197/70743415-89470980-1cd4-11ea-81de-e7520326e8c9.png)

## What is the expected result?
Right menu sticks to the top of the browser.

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.0.0  |
| IE|         |

**Comment by matuzalemsteles** [comment] 2020-09-23 19:23
I'm closing this since it has already been fixed and it's not being reproducible anymore. Feel free to reopen if it is still reproducible. Thanks!

**Closed by matuzalemsteles** 2020-09-23 19:23 UTC
Labels: browser: ie, comp: clayui.com, type: bug
