### ISSUE TITLE
[ClayCssUtilities classes for 

### ISSUE THREAD

**Issue by eduardoallegrini** [liferay/clay#2992] opened 2020-03-11 08:06 UTC
Hi guys, recently I've been working on the Questions project https://issues.liferay.com/browse/LPS-109146 During this project I had to restyle the app and I had to choose between custom classes and Bootstrap's utility classes.

I started with the custom classes and then I switched to ultilities because we had a short deadline and the project was oriented towards a POC. The difference of working with utilities classes is really relevant, the markup creation is so fluid and fast, the responsiveness is ready to be defined and most of the styles that we need already exists.

In conclusion I think we should allow and recommend the use of the utilities classes in our projects.

The problem is that at the moment (in Bootstrap 4) most of the classes have the important attribute, while In Bootstrap 5 is optional (thanks to a Marcos' request https://github.com/twbs/bootstrap/pull/29625)

So my idea is to either to backport their update from Bootstrap 5 or create our own utilities classes in Clay as we did as a test for the spacing ones https://github.com/liferay/clay/issues/2725

**Comment by pat270** [comment] 2020-03-11 21:13
Closing, this is a duplicate of https://github.com/liferay/clay/issues/2993

**Closed by pat270** 2020-03-11 21:13 UTC
Labels: rfc
