### ISSUE TITLE
ClayCard need new type of card `card-type-template`

### ISSUE THREAD

**Issue by pat270** [liferay/clay#1865] opened 2019-04-16 17:35 UTC
https://issues.liferay.com/browse/LPS-91668 is using the wrong type of card.

https://lexicondesign.io/docs/patterns/cards/cardsNavigation.html
http://pat270.github.io/lexicon/v2.10.0/content/test-card-type-template/

**Comment by matuzalemsteles** [comment] 2019-04-17 14:39
hey @pat270 I think this should be a new variation of the Cards for the Main Types examples. It looks like the markup runs a little bit out of what we currently have for ClayFileCard, ClayImageCard, and ClayUserCard.

**Comment by pat270** [comment] 2019-04-17 17:50
@matuzalemsteles ClayCard is too strict with class names on the container. We should move the class `card-type-asset` to `ClayFileCard`, `ClayImageCard`, and `ClayUserCard`. I'm using `ClayImageCard` as example, we should output the classes `card-type-asset image-card` by default but allow it to be overwritten by some parameter. That way we're not locked into `card card-type-asset image-card` and devs can take advantage of our plugin to create their own custom cards.

The same thing applies to `ClayHorizontalCard` output `card-type-directory` by default but allow it to be overwritten by some parameter.

**Comment by matuzalemsteles** [comment] 2019-04-17 18:16
Yeah, we can improve this to not be so strict, the problem is that we would have to add many APIs to be customizing the class names. But I talked to @jbalsas and let's create this variation only in 3.x, let's look carefully for it there.

**Comment by matuzalemsteles** [comment] 2019-06-10 22:45
I'm closing this once it was fixed with the implementation in React #2007

**Closed by matuzalemsteles** 2019-06-10 22:45 UTC
Labels: 2.x, 3.x, comp: clay-components
