### ISSUE TITLE
Multi select input behavior on string with commas paste

### ISSUE THREAD

**Issue by victorvalle** [liferay/clay#1569] opened 2019-02-19 08:13 UTC
There is a behavior that is not working well. When I try to paste this string "one, two, three" in the field, the expected result is:
[one][two]three

Current behavior:
I have to paste three times so I get the previous result.

Please see the attached file

[multiselectpaste.zip](https://github.com/liferay/clay/files/2878990/multiselectpaste.zip)

**Comment by matuzalemsteles** [comment] 2019-02-19 13:06
hey @victorvalle, This is working fine in the most current version of Clay, I've been investigating to know the real cause of the problem, this is a problem in implementing MultiSelect in the TagSelector of Liferay.

hey @jbalsas, it seems that `this.addCallback` does not exist in `window` it is breaking javascript and makes MultiSelect not working after that. Something like `_com_liferay_journal_web_portlet_JournalPortlet_null` is coming.

https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-taglib/src/main/resources/META-INF/resources/asset_tags_selector/js/TagSelector.es.js#L87

**Comment by matuzalemsteles** [comment] 2019-02-25 21:19
hey @victorvalle I'm closing the issue since the problem is not in Clay.

**Closed** 2019-02-25 21:19 UTC
