### ISSUE TITLE
[ClayCSS] Table title horizontal alignment behavior differs from Chrome to Safari

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#2219] opened 2019-07-24 20:28 UTC
The left page is running on Chrome and right, on Safari.
<img width="1261" alt="Screen Shot 2019-07-24 at 17 21 39" src="https://user-images.githubusercontent.com/7663513/61825891-a23f4300-ae37-11e9-9656-9fd6f04edbc3.png">

Same comparison on https://next.clayui.com/docs/components/table.html

<img width="1249" alt="Screen Shot 2019-07-24 at 17 23 47" src="https://user-images.githubusercontent.com/7663513/61825961-c733b600-ae37-11e9-8e5d-1342cf5a5d41.png">

Debugging, we are computing `text-align: start;` on Safari and `text-align: inherit;` on Chrome. Disabling this property on Safari's debugger, apparently fixed it. 
https://recordit.co/MxOMjKswBy

/cc @pat270 @brunofarache

**Comment by brunofarache** [comment] 2019-07-24 22:37
Thanks for creating this @diegonvs!

Fix should be merged to DXP as it affects all tables.

**Comment by pat270** [comment] 2019-08-21 18:21
This is caused by https://github.com/liferay/clay/issues/1743

**Comment by zhangyan0701** [comment] 2019-08-22 10:05
Create https://issues.liferay.com/browse/LPS-100174 for this issue.

**Closed** 2019-08-22 15:01 UTC
Labels: 2.x, 3.x, browser: safari, comp: clay-css, type: bug
