### ISSUE TITLE
@clayui/drop-down: Tabbing through a dropdown menu returns focus to beginning of page

### ISSUE THREAD

**Issue by pat270** [liferay/clay#5147] opened 2022-10-18 18:43 UTC
https://clayui.com/docs/components/drop-down.html

1) Open the dropdown menu
2) Press tab to cycle through each item
3) When reaching the end of the menu, focus returns to the browser's tab

Not exactly sure what it's supposed to do.

- Return to the first item in the menu?
- Close the dropdown and focus the next element?

**Comment by dsanz** [comment] 2022-10-20 11:55
@drakonux what do you think about this behavior?

**Comment by matuzalemsteles** [comment] 2022-10-20 17:18
In fact, the behavior here is to close the DropDown and the focus goes back to the trigger, this already happened before but we had a regression, I think it was due to the implementation of moving the focus to the first menu item, it caused some problem, I'm investigating that.

**Comment by marcoscv-work** [comment] 2022-10-20 17:45
It should go to the next element since we have looped through the entire content of the dropdown.

The perfect interaction is represented here:
https://getbootstrap.com/docs/4.6/components/dropdowns/#single-button

More important keyboard interactions:

When we press enter or space in the trigger button:
 - dropdown is opened and focus still in the button, in order to make aviable press space/enter one more time and close the menu
 - At this point with the menu opened we can press tab or arrow down to start looping the menu items
   - Menu can be always closed by `Esc`
   - If we use `arrows`, navigation through the menu is cyclic
   - If we use `tab` key we go along all menu items and finally getting out from the last one, the menu is closed and focus go to the next element (from the original dropdown trigger)

**Comment by matuzalemsteles** [comment] 2022-10-20 17:55
@marcoscv-work yeah, that true deve mover para o proximo elemento focavel depois do trigger do button.

> If we use tab key we go along all menu items and finally getting out from the last one, the menu is closed and focus go to the next element (from the original dropdown trigger)

I'm not sure about this behavior, in the last revision I did, we do it wrong the `tab` should not navigate the menu https://www.w3.org/WAI/ARIA/apg/example-index/menu-button/menu-button-links, the behavior is that when using tab key, it should move to next focusable element on screen instead of menu, menu is just navigable in loop using arrow keys and moving focus. This type of navigation is also different when you have an autocomplete that has the Menu, the focus is on the trigger or input when the aria-activedescendant property changes.

About these behaviors I will leave it to the issue #5041.

**Comment by marcoscv-work** [comment] 2022-10-20 17:55
About https://github.com/liferay/clay/issues/5041

We would be probably adding comments there :-(

I like https://www.w3.org/WAI/ARIA/apg/example-index/menu-button/menu-button-links
The only notable difference is when opening the menu and moving the focus to the first item, in that case the readers is a 
a little bit confusing reading the state change and the option focused, that's the reason I think is better keep the focus in the trigger and then, knowing the menu is opened use tab or arrows to navigate

**Comment by marcoscv-work** [comment] 2022-10-20 17:55
15 sec comment difference, hahaha

**Comment by marcoscv-work** [comment] 2022-10-20 17:59
Both behaviours are valid and very similar, we can choose any of them and it will be a correct decision, just take the one make us feel more comfortable and be able to defend the decision, something to add @drakonux ?

**Comment by drakonux** [comment] 2022-10-21 03:34
The spec is unclear about these specific details, but let´s see.

**About the screen reader**
I think the easy option is to choose the option that clearly tells the user what's happening. But, it's not our bias @marcoscv-work about the SR. Is it a mess for SR users? They are used to using it in that way 🤷. 

**About the focus trap**
I agree with @matuzalemsteles . We do it wrong the tab should not navigate the menu items. Instead, it should go to the next focusable element. At least, what the specs say it's that. The menu is just navigable in loop using arrow keys.

Ps. Just for clarification, do we all agree that the focus should not be shown until the user interacts with the keyboard?

**Comment by marcoscv-work** [comment] 2022-10-21 09:55
**About the screen reader**:
The specs only say that it must be understandable, so messy reading has to be avoided

**About the focus trap**:
Arrows are defined to navigate in the context of a `widget` (called widget to a component with its own functionality), for example dropdown menu, tabs, etc.
To go ahead to the next focusable element just use tab key
To close any menu or loop interaction we also can use `esc` key
Screen readers like JAWS ignores the use of arrows since JAWS arrows navigates elements lineally, so it is not a blocker for SRs, just a help for movement by keyboard following the standard (determinate by ARIA roles)

**About the focus and mouse**:
Sí, el enfoque debe usarse cuando usamos el teclado y tenemos que distinguir muy bien entre el estado hover, focus con mouse, focus con teclado

**Comment by marcoscv-work** [comment] 2022-10-21 11:40
I'm going to try to explain the difference between patterns with focus to the fist element and dont move the focus until press tab or arrows (with menu opened):

Pattern: **Focus auto move to the first item**:

1. SR reads click me, I'm a popup collapsed button:
<img width="755" alt="image" src="https://user-images.githubusercontent.com/7963804/197184534-2d380dcb-578d-4b24-aa6a-a175816461d3.png">
2. We press the button and directly the SR reads: Button (or any first item).
<img width="753" alt="image" src="https://user-images.githubusercontent.com/7963804/197184926-90c58a5b-eac3-4810-b417-62921564b8ed.png">

Pattern:  **Keep the focus on the trigger and reads its change**:

1. SR reads click me, I'm a popup collapsed button:
<img width="755" alt="image" src="https://user-images.githubusercontent.com/7963804/197184534-2d380dcb-578d-4b24-aa6a-a175816461d3.png">
2. We press the button and the SR reads the state change.
<img width="753" alt="image" src="https://user-images.githubusercontent.com/7963804/197185982-3754e4b8-b426-4705-8b0c-ad1082f71601.png">
3. Now we press arrow down or tab and we get in the first item and it is read:
<img width="753" alt="image" src="https://user-images.githubusercontent.com/7963804/197184926-90c58a5b-eac3-4810-b417-62921564b8ed.png">


### Using JAWS:

It's the same, but the state change is read shorter:
Pattern: "Key you pressed / state changed"

**Focus auto move to the first item**:
1. SR reads click me, I'm a popup collapsed button:
2. We press the button and directly the SR reads: Button (or any first item).
"Enter - Button" (the first button/link in dropdown)

1. SR reads click me, I'm a popup collapsed button:
2. We press the button and the SR reads the state change.
"Enter - Expanded"
3. Now we press arrow down or tab and we get in the first item and it is read:
"Button" (the first item in dropdown)


## Conclusion:

For me the pattern: **Focus auto move to the first item** can be even sometimes difficult to understand.

**Comment by matuzalemsteles** [comment] 2022-10-21 15:19
@marcoscv-work This makes sense, in situations like Drilldown where the user is parachuted into an element that has no contextual information. I thunk this I think makes more sense for a menu with a simple list of options. Maybe we leave this set up or cases like Drilldown keep the focus on the trigger and DropDown with an options menu moves to the first `menuitem` option.

And we probably need to add APIs in Drilldown to configure the aria-labels of these buttons too 😅.

**Comment by matuzalemsteles** [comment] 2022-10-21 17:26
Hey guys, this issue was closed automatically due to the PR that merged to fix the first issue of this issue, since the other things are still under discussion I think we better move this discussion to the issue #5041

**Closed** 2022-10-25 00:37 UTC
Labels: type: bug, comp: accessibility, comp: clay-components
