### ISSUE TITLE
Changelog Updates Proposal

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#3898] opened 2021-01-21 19:09 UTC
### The Problem

It's difficult for DXP devs to know when a clay feature or issue has been resolved and available in DXP. This is likely due to an issue of traceability and discoverability.

#### Current Process

If a DXP dev has created an issue in this repo and sees that a fix is merged and thus closing their ticket. In order to determine if that fix is in DXP they would need to check the following.
- Is it released yet? Check if there has been a release since that PR has been merged.
- If released, check the version released for that module.
- Go to DXP and check if that version exists in `frontend-taglib-clay/package.json` for the given module.

However, that is more of a "clay centric" approach and requires the dev to know their way around the clay repo and assumes they had an issue they are specifically curious about.

More often than not, I think people just want to know "whats in the latest release?" when they see an LPS ticket in DXP with "Update @clayui/* dependencies". In order to know that a dev would need to look at the list of packages released and then go to each individual changelog. If 10+ packages have been released, this requires 10+ different docs and isn't ideal.

#### Proposal 

In order to fix this, I think we can implement a few processes to address this.

1. Use GH actions to automatically label issues with the "fix version". Each release we would spawn a GH action that would apply labels(something like `@clayui/label@v3.5.0`) to each issue that was fixed by the current release.
2. Generate more helpful changelogs for each package. I think we need to not only link to the commit, but also the issue that the commit stemmed from.
3. Generate a "global" changelog for each release. This would live at the root of the clay repo, and it would include the list of issues fixed after each publish. Example below
4. Copy/paste the global change log changes to the LPS ticket that is used to merge the release into DXP.

 --------
# Global Change Log

#### Bug Fixes

-   Close icon should be times-small (#3879)

#### Features

- Supports type `null` for displayType (#3896)

-------

#### Conclusion

I think if we adopt these changes (most of which would be automated), it would significantly increase the traceability and discoverability of what is released and how to know if it's available in DXP.

**Comment by matuzalemsteles** [comment] 2021-01-21 22:20
> 1. Use GH actions to automatically label issues with the "fix version". Each release we would spawn a GH action that would apply labels(something like `@clayui/label@v3.5.0`) to each issue that was fixed by the current release.
> 2. Generate more helpful changelogs for each package. I think we need to not only link to the commit, but also the issue that the commit stemmed from.

I especially like these changes! If can help, in GH Actions once the issue is linked to a PR that has been merged, we can add a comment to the issue with some friendly message, giving instructions on when that issue will come out in the release.

Something like: _"The issue has been fixed and merged into the master and scheduled for the next release a label for the corresponding release will be added when it is released."_

**Comment by brunofernandezg** [comment] 2021-01-22 07:49
> 3. Generate a "global" changelog for each release. This would live at the root of the clay repo, and it would include the list of issues fixed after each publish. Example below
4. Copy/paste the global change log changes to the LPS ticket that is used to merge the release into DXP.

I like those two :p A single changelog, and pasting it on the LPS tickest (and also use the information for the new release communications) would be very useful. We would have the same information in github, Jira and internal communication channels and tracking changes would be much easier

**Comment by wincent** [comment] 2021-01-22 08:13
I'm glad you're discussing this because I also brought it up in https://github.com/liferay/clay/issues/3849:

> Finally, there's the question of visibility, where even if things were to arrive at a regular cadence in liferay-portal, people outside of our team (and [even sometimes inside of it](https://liferay.slack.com/archives/G3JBR21HA/p1607959040102400?thread_ts=1607958744.102300&cid=G3JBR21HA)) don't know when the next release is going to arrive or what is included in it. We have a general problem with traceability (as tickets move from LEXI to GitHub issues to LPS, and changes themselves move from fork to fork). Code itself arrives in liferay-portal via an npm install, so one cannot directly tell what is in the repo at any given time, or what is included in an update — the only visible trace is in a set of version numbers ([example](https://github.com/brianchandotcom/liferay-portal/pull/96862)). If one wants to inspect the changelog, there may be as many as 40 separate files to inspect because each package has its own and we have a lot of packages. And when you do get in to a changelog, you may find that the "update" is [basically empty like this one](https://github.com/liferay/clay/blob/master/packages/clay-autocomplete/CHANGELOG.md#321-2020-12-02) (a Lerna-generated thing that says "Version bump only"). For an engineer, figuring out what particular Clay code is in effect in liferay-portal really means looking up a version number, downloading an npm module, and looking at the built artifact; note that you can't actually look up packages by tags in the GitHub repo any more because we don't currently publish per-package tags (ie. given a version number and a package name, you cannot jump directly to the corresponding code in the repo; instead, you have to carefully select the commit corresponding to the release date and the corresponding `chore(release)` commit).

One thing to consider is that if we do end up moving Clay into liferay-portal, the visibility/traceability aspects will be totally different; ie. I imagine fixes/features will all have a one-to-one relationship with LPS tickets, which means that if a PR for an LPS is visible in `master`, then the change is available... "releases" as a concept won't really matter at all on `master`, nor will changelogs etc. In the same way that we don't ask "what version of `layout-content-page-editor-web` has the fix for LPS-XXXXXXX?", we wouldn't ask that question for Clay; it would just be a question of "is LPS-XXXXXX in `master` yet?".

Of course, we can still publish to npm (for use in other repos, and also because we might — depending on how we evaluate the tradeoffs — want to backport changes to older branches via npm releases as opposed to backporting code changes), so this doesn't relieve us from the need to improve our changelogs; but it might change the relative urgency of it. For example, if we decide to merge into DXP "soon", maybe we don't do anything right now; on the other hand, if we judge that we can make these improvements cheaply and don't anticipate moving anything for a while, then that changes the calculus.

**Comment by bryceosterhaus** [comment] 2021-01-28 19:16
First part of this is merged, adding the global changelog. Now just working on automating labels or comments for issues to signal that they have been released.

**Closed** 2021-02-03 18:03 UTC
Labels: 3.x, rfc
