### ISSUE TITLE
ClayPopover css markup not aligned with trigger button when the page's dir is rtl

### ISSUE THREAD

**Issue by gabrielpramos** [liferay/clay#3669] opened 2020-08-28 20:58 UTC
-   [x] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?
Use ClayPopover css markup within a page with rtl dir

## What is the expected result?
the popover will be unaligned with the trigger button

| Tech  | Version |
| ----- | ------- |
| React | v16.12  |

**Comment by gabrielpramos** [comment] 2020-08-28 21:00
this bug might be fixed removing the right attribute from .popover class when html has rtl dir or adding right:auto instead of removing

html.rtl .popover{
   right: auto;
}

**Comment by bryceosterhaus** [comment] 2020-09-01 19:23
@gabrielpramos is this for any page or portal specific? Is this reproducible in codesandbox?

**Comment by matuzalemsteles** [comment] 2020-09-04 15:33
@bryceosterhaus I think this is reproducible on any page of the portal, it will probably also be reproduced in a codesandbox cc @pat270

**Comment by pat270** [comment] 2020-09-04 16:22
I think the easiest fix is to check for `dir="rtl"` and have `@clayui/popover` render `right` for left and `left` for right. The css should be flipped because it goes through the rtl converter.

**Comment by matuzalemsteles** [comment] 2020-09-04 18:52
@pat270 I'm thinking why this doesn't happen with DropDown for example, we didn't need to change anything inside the component, in Popover we use the same DropDown alignment strategy.

**Comment by pat270** [comment] 2020-09-04 19:03
It looks like we updated some CSS in Portal? https://github.com/liferay/clay/pull/3022 should have some detail about it.

**Comment by matuzalemsteles** [comment] 2020-09-04 19:44
Hmm, maybe we should make this change on the Portal? looking at the conversation now it seems that this was reversed in Clay and went to the Portal.

**Comment by john-co** [comment] 2020-09-04 23:52
linked to reported LPS bug ticket: https://issues.liferay.com/browse/LPS-120102

**Comment by matuzalemsteles** [comment] 2021-09-01 16:20
Closing this, it was fixed with the implementation of #4241

**Closed by matuzalemsteles** 2021-09-01 16:20 UTC
Labels: type: bug, comp: clay-css, 3.x
