### ISSUE TITLE
Clayui.com documentation, how enhance it? 🤔

### ISSUE THREAD

**Issue by diegonvs** [liferay/clay#1111] opened 2018-08-27 17:51 UTC
I've fill this issue to share some thoughts and start a discussion about how we can improve our website docs.

- We will work on integration of `clay-paver` on clayui.com. So, we are thinking of putting it on another page so we do not conflict with other css files, do you guys have any suggestions?

- Our LATAM design intern @gabbebarbosa, had made a document during his internship rotation describing some enhancements on clay docs website.

Check it out here:

![documentation-clay](https://user-images.githubusercontent.com/7663513/44673606-68d13e00-aa02-11e8-9f66-0e7ca72774d2.png)
Note that she had put a table with some API description on each component.

Also, she said that would be great for us have a section to fill a issue if the provide documentation is wrong. I've noticed that we have a icon that redirect to Github issues but isn't too much.

- Last weekend i attended to [Braziljs conf](https://braziljs.org/conf/) and i talked too much with a lot of Front End developers, including a girl that works on a company that has a design pattern system and component library similar our. She said that a lot of problems using a design system on his company was solved by: 
  - A good documentation, including API full description like: http://circuit.sumup.com/#/components/blockquote. I think Gabbe's layout work will solve it.  
  - A place to workbench API like Storybook, @matuzalemsteles had built a utility to use this feature on current documentation with /try page. Like: http://circuit.sumup.com/storybook/
  - A section to include Best Practices for each component.

/cc @pat270  @matuzalemsteles @jbalsas @marcoscv-work

**Comment by matuzalemsteles** [comment] 2018-08-29 13:40
I think it's worth exposing an API table in each component on the pages, people are starting to use it and they are missing something to be able to walk. They are lost in how to use...

I also like the idea of exposing a good practice session, but maybe not for all the components but some other session.

**Comment by jbalsas** [comment] 2018-08-29 14:57
Hey @matuzalemsteles, I really like the idea of having the API table exposed. We developed an [electric task to automatically generate the API page](https://github.com/electricjs/electric/blob/master/packages/electric/lib/tasks/api.js). You can see it in action in [AlloyEditor > API](https://alloyeditor.com/api/1.5.0/). 

Could you guys figure out how this would work for our Gatsby site? Ideally, it should be autogenerated from our jsdoc, so we don't need to write it twice... what do you think?

**Comment by matuzalemsteles** [comment] 2018-08-29 15:41
@jbalsas yes I've been thinking of something similar, but not having a page just for that, but on every page of the component but automatically without having to change something at hand.

**Comment by jbalsas** [comment] 2018-08-29 16:00
Sounds good to me try it out separated by components. Let's see how to make that happen! :)

**Comment by jbalsas** [comment] 2018-09-05 14:44
Hey @matuzalemsteles, @diegonvs, now that we've pushed through with the API docs for the components, and while we discuss how to [Improve the clayui.com deploy process](https://github.com/liferay/clay/issues/1170), could you guys focus on the following, please?

- [ ] Incorporate the contents from http://pat270.github.io/lexicon/ into these sections so we can remove it. Only things that serve as developer reference should be published to the site and it all should live in the same site
- [ ] @pat270 has been using http://pat270.github.io/lexicon/ for local development and smoke testing. We should set this up somehow so it can be used locally within the clay-css package, but without the risk of producing a live site. @pat270, can you share with @diegonvs and @matuzalemsteles what you need so they can help you out here?

Just today we had again an issue where someone was looking how to create a simple loading indicator and had to end up looking at http://pat270.github.io/lexicon/content/loaders/ rather than https://clayui.com

This is our biggest barrier on usage and consistency. We need to address this

Please, could you take a look at the structure proposal and go through the current docs to merge in what's not in the right place and see what should be brought over from @pat270's site?

After we're done with this, we should be able to redirect the other site to https://clayui.com

**Comment by matuzalemsteles** [comment] 2018-09-06 12:35
> Only things that serve as developer reference should be published to the site and it all should live in the same site

hey @jbalsas this part was not very clear to me. Could you clarify a little more 😅? what contents should move?

> @pat270 has been using http://pat270.github.io/lexicon/ for local development and smoke testing. We should set this up somehow so it can be used locally within the clay-css package, but without the risk of producing a live site.

hey @pat270, @jbalsas what do you have in mind about this? I've been thinking about creating a link from the `clay-css` package to `clayui.com` in a task, this can help @pat270 to be able to work from the site without sending the changes to production. Maybe we can also try to create certain pages appear only in development environment, I do not know if this would really solve the problem, I would like to hear your ideas on this.

**Comment by matuzalemsteles** [comment] 2018-09-06 13:08
hey guys, it's just a thought: Since @pat270 can use the site `clayui.com` for tests and experiments for future versions, we can create **Clay Nightly** (Just a code name) that will stay in another environment of WeDeploy, the idea is that @pat270 continue developing on clayui.com but we can create a configuration for Gatsby to hide pages marked as `Nightly`...

* **Nightly** - Future versions of Clay, an area for experimentation and testing of things that may not be released... This can help other people view and be able to give their opinion.

What do you think?

**Comment by jbalsas** [comment] 2018-09-07 07:32
Hey @matuzalemsteles!

We need to separate the concepts. 

**Documentation** needs to be thoroughly thought out. It needs to have a purpose and be presented in a way that can be found, searched, consumed and shared with developers. **We need to be making conscious decisions as to what we document**, because those are the things we need to maintain and support.

> Only things that serve as developer reference should be published to the site and it all should live in the same site

This means that we need to think of what's our API, what do we want to expose and get people to use and in which ways?

**Development** process does not need to be documented. We need to figure out what's the best way to develop and test css. For the moment, @pat270 has a clear workflow that we should maintain, but **that development workflow should have no impact on what is documented**. In the future, we should try to improve our process to add automated regression testing and different approaches that don't involve manually checking everthing over and over.

Makes sense?

**Comment by jbalsas** [comment] 2018-09-12 09:04
Hey @matuzalemsteles, thanks for the answer and additional feedback! 👍 

**Documentation**

On the `CSS` side, we need to document things that CSS/HTML developers might need, such as [mixins](https://github.com/liferay/clay/tree/master/packages/clay-css/src/scss/mixins), [helpers](https://github.com/liferay/clay/tree/master/packages/clay-css/src/scss/functions), special classes...

Documenting `variables` would be a huge and probably useless effort (we have soooo many of them). I think we could simply have a page with an introduction for that with a link to the `Clay Paver` page where we can more effectively play around with variables.

The last bit is that we need to have all the markup documented along with the components. If some are not part of Lexicon but we still want to document additional markup, then we could add a special section "others" or "satellites".

**Development**

Sounds good to me, please, sync with @pat270 and let's work on a proposal for our internal development workflow. Keep in mind that we want others like @marcoscv-work and yourself to also contribute there :)

I'm happy if we can settle on the manual process for now. We can think about automating some things in the future. @john-co should be able to start thinking about it as well :)

**Comment by diegonvs** [comment] 2018-09-17 20:06
I think that we need a way to show users our supported browsers. I didn't find anything unless give a table with supported browsers like google/material-design-lite. Do you have any suggestion guys?

**Comment by matuzalemsteles** [comment] 2018-09-18 21:04
hey guys,

I do not know if we have to follow the "Lexicon Core Components" session with the Lexicon session, we are leaving aside some extension components of Clay Charts, we have to document and say that they exist. Any suggestions on this?

cc @jbalsas

**Comment by matuzalemsteles** [comment] 2018-09-19 14:10
Ah sorry, I was not so clear! 😅

Since we will follow the proposal to organize the documents of the `Components` session, we will have to remove some docs. What we will do with the **Radar**, **Geomap** and **Scatter** documentation for example. Can we create a Charts extension session? within the `Charts` session.

**Comment by jbalsas** [comment] 2018-09-19 15:11
Hey @matuzalemsteles, makes sense now!

I think in this case this is more of something missing in Lexicon. They will be working to add it to their documentation, so we can keep it as it is for now.

**Closed** 2018-10-03 14:12 UTC
Labels: clayui.com, docs
