### ISSUE TITLE
Content in Card page is squished to the left on IE

### ISSUE THREAD

**Issue by nkkwon** [liferay/clay#2796] opened 2019-12-12 20:49 UTC
-   [ ] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## What are the steps to reproduce?
Open documentation on IE and go to the Card section in Components

## What is the expected result?
Should be able to see page content, but page format is broken and everything is squished to the left

![Screenshot from 2019-12-12 12-47-58](https://user-images.githubusercontent.com/33915312/70747930-d8456c80-1cdd-11ea-96f4-a02c764e004c.png)

## Environment

| Tech  | Version |
| ----- | ------- |
| Clay  | v3.0.0  |
| IE |         |

**Comment by matuzalemsteles** [comment] 2020-09-23 19:24
I'm closing this since it has already been fixed and it's not being reproducible anymore. Feel free to reopen if it is still reproducible. Thanks!

**Closed by matuzalemsteles** 2020-09-23 19:24 UTC
Labels: comp: clayui.com, device: mobile, type: bug
