### ISSUE TITLE
Pagination bar Page size selection DropDown is not positioning correctly

### ISSUE THREAD

**Issue by marco-leo** [liferay/clay#1428] opened 2019-01-08 23:21 UTC

**Comment by matuzalemsteles** [comment] 2019-01-16 15:50
hey @marco-leo, could you give us an example to be able to reproduce the use case?

**Comment by jbalsas** [comment] 2020-01-20 15:57
Doing some spring-cleaning... closing all issues labeled as 2.x that are not type:bug since 2.x is in maintenance and we won't be proactively be taking these ones.

@marco-leo, feel free to add to the conversation and/or reopen if you think this is still relevant, if it is a current bug in `2.x` or if it affects our new `3.x` components so we can add it to the mix.

Thanks!

**Closed by jbalsas** 2020-01-20 15:57 UTC
Labels: 2.x, comp: clay-components
