### ISSUE TITLE
Question: Will breakpoints ever be readjusted for new devices?

### ISSUE THREAD

**Issue by fortunatomaldonado** [liferay/clay#1837] opened 2019-04-10 16:13 UTC
With larger mobile devices, some desktop components are being displayed instead of the mobile components.
An example is the iPhone 10 in landscape mode will display desktop components. Is this considered acceptable due to the already established breakpoints or will readjustments be needed due to it still being mobile?

Visuals of this can be found here: https://issues.liferay.com/browse/LPS-93545

**Comment by pat270** [comment] 2019-04-10 20:48
@fortunatomaldonado This is working as intended. We collapse and show based on screen size and not device. Bootstrap and Lexicon Design trigger the mobile view at <= 767px. 

If you want to change the breakpoint for 7.0: 
###### _aui_variables.scss
```
$screen-sm-min: 813px;
```
also need to update https://github.com/liferay/liferay-portal/blob/7.0.x/modules/apps/foundation/frontend-css/frontend-css-common/src/main/resources/META-INF/resources/liferay/_variables.scss#L10 so it applies to css provided by widgets.

for 7.1, 7.2
###### _clay_variables.scss
```
$grid-breakpoints: (
  xs: 0,
  sm: 576px,
  md: 813px,
  lg: 992px,
  xl: 1200px
);
```
also need to update https://github.com/liferay/liferay-portal/blob/7.1.x/modules/apps/frontend-css/frontend-css-common/src/main/resources/META-INF/resources/liferay/_variables.scss#L9

Changing these values will serve the mobile view to tablets in portrait mode (e.g., ipad, samsung galaxy)

**Comment by fortunatomaldonado** [comment] 2019-04-10 20:59
Thank you for the information, @pat270. It is truly helpful as always!

**Comment by duracell80** [comment] 2019-04-15 14:13
Solution rejected, Can this be addressed urgently for 7.2 please? We can make the change in theme but we shouldn't have to.

**Comment by fortunatomaldonado** [comment] 2019-04-15 16:23
Hello @pat270,

If I may ask another question:
I understand that the screen size dictates what will be displayed and not the device itself, but it does seem that these breakpoints were made with tablets in mind. As for larger mobile devices, it does seem strange to me to have desktop view components with smaller length as it can be difficult at times to use.

Will these breakpoints be reconsidered for user experience and find a middle ground for tablets and mobile devices?

Thanks in advance.

**Comment by duracell80** [comment] 2019-04-15 16:28
`// iPHONE 10 LANDSCAPE
@media only screen 
and (min-device-width : 375px) 
and (max-device-width : 812px) 
and (-webkit-device-pixel-ratio : 3)
and (orientation : landscape) { /* STYLES GO HERE */
    
  }
}`

What about designing the breakpoints for devices / orientation as an add on that can be @imported on top of the current breakpoints?

**Comment by duracell80** [comment] 2019-04-15 17:45
Liferay support won't touch this at all = "Customization" because I changed a number it's now my personal problem. The suggestion is incomplete because while the nav does collapse, it's still the desktop nav behind it so in Landscape the navigation goes unobtainium,

What else is causing the nav to snap to desktop?

![ack](https://user-images.githubusercontent.com/18121278/56153575-256d1500-5f7c-11e9-8123-4ff2297055b2.gif)

This should be a solution from Liferay is base theme, not forced onto customers as customization that becomes "unsupported".

**Comment by pat270** [comment] 2019-04-15 19:42
@duracell80 `_aui_variables.scss` only applies to the theme. I've been testing on 7.0.x and I don't have no solution for you this at the moment. It's the way we are using `frontend-css-common` (not 100% sure tho). It seems like each module is pulling in a published version of `frontend-css-common`, modifying the source and deploying has no impact on any of the media queries set in any module `main.scss`. There probably is some workaround, but I don't know myself. I pinged a few people to see if they can give me some more info.

For your theme specific CSS issue, I have a hack. In your theme create a file:

###### src/css/_mixins.scss
```
// Hack that overwrites variables and mixins provided by `frontend-css-common`

$screen-lg: 1200px !default;
$screen-lg-min: $screen-lg;
$screen-lg-desktop: $screen-lg-min;

$screen-md: 992px !default;
$screen-md-min: $screen-md;
$screen-desktop: $screen-md-min;

$screen-sm: 813px !default;
$screen-sm-min: $screen-sm;
$screen-tablet: $screen-sm-min;

$screen-xs: 480px !default;
$screen-xs-min: $screen-xs;
$screen-phone: $screen-xs-min;

$screen-md-max: ($screen-lg-min - 1) !default;
$screen-sm-max: ($screen-md-min - 1) !default;
$screen-xs-max: ($screen-sm-min - 1) !default;

$media-query-sizes: (
	xs: $screen-xs,
	sm: $screen-sm,
	md: $screen-md,
	lg: $screen-lg
);

// Deprecated

$breakpoint_phone: 768px !default;
$breakpoint_tablet: 980px !default;

@mixin media-query($min, $max: null) {
	$maxWidth: -1;
	$minWidth: -1;

	@if $min != null {
		@if map-has-key($media-query-sizes, $min) {
			$minWidth: map-get($media-query-sizes, $min);
		}
		@else {
			$minWidth: $min;
		}
	}

	@if $max != null {
		@if map-has-key($media-query-sizes, $max) {
			$maxWidth: map-get($media-query-sizes, $max);
		}
		@else {
			$maxWidth: $max;
		}
	}

	@if $maxWidth <= 0 and $minWidth <= 0 {
		@content;
	}
	@else if $maxWidth <= 0 {
		@media (min-width: $minWidth) {
			@content;
		}
	}
	@else if $minWidth <= 0 {
		@media (max-width: $maxWidth) {
			@content;
		}
	}
	@else {
		@media (min-width: $minWidth) and (max-width: $maxWidth) {
			@content;
		}
	}
}

// Shortcuts

@mixin xs {
	@include media-query(xs) {
		@content
	};
}

@mixin sm {
	@include media-query(sm) {
		@content
	};
}

@mixin md {
	@include media-query(md) {
		@content
	};
}

@mixin lg {
	@include media-query(lg) {
		@content
	};
}
```

> What about designing the breakpoints for devices / orientation as an add on that can be @imported on top of the current breakpoints?

We can't provide anything like this due to Bootstrap. Their grid framework doesn't allow passing in custom media queries.

**Comment by duracell80** [comment] 2019-04-15 19:49
Thank you. It felt like something was coming in from combo.css so that could be it, given that navigation is a portlet?

**Comment by pat270** [comment] 2019-04-15 21:07
Navigation Portlet is an exception. I believe it just provides markup and the CSS is in the theme. See https://github.com/liferay/liferay-portal/tree/7.0.x/modules/apps/web-experience/site-navigation/site-navigation-menu-web/src/main/resources/META-INF/resources there is no main.scss file for that module.

**Comment by fortunatomaldonado** [comment] 2019-04-19 16:18
Hello @pat270,

So the hack is currently necessary if one wants to adjust the breakpoint, is this correct? Has there been any news about `frontend-css-common`?
Thank for the help.

**Comment by pat270** [comment] 2019-04-22 17:03
@fortunatomaldonado that hack only adjusts the breakpoint for theme files that use the `frontend-css-common` mixin. Widget Sass that use `frontend-css-common` mixins won't be adjusted, I'm still waiting for word on how to work around it. /cc @jbalsas

**Comment by jbalsas** [comment] 2019-04-23 14:55
hey @pat270, did you test this out in `master`? I think we addressed this there, so we can tweak the build for previous versions if necessary.

**Comment by pat270** [comment] 2019-04-24 23:48
@jbalsas I just tested and I can't seem to get it to update.

**Comment by kresimir-coko** [comment] 2020-05-25 14:17
@pat270 Maybe we should close this as it's been a year, leaving it up to you since you're the one that last handled it.

**Comment by pat270** [comment] 2020-05-26 18:20
Thanks for the reminder @kresimir-coko!

We can close this. I'm going to leave some notes just in case someone runs into something similar to this. We deprecated `@mixin media-query` and `@mixin respond-to` in Liferay Portal 7.2.1 GA2. I searched the 7.2.1 GA2 branch and couldn't find any uses in the code. We now use Bootstrap's `media-breakpoint-up` and `media-breakpoint-down` media-query mixins everywhere.

Unfortunately this issue is still relevant in Liferay Portal. Customizing the breakpoint sizes in the theme will have no effect on module css such as `modules/apps/product-navigation/product-navigation-control-menu-theme-contributor/src/main/resources/META-INF/resources/product_navigation_control_menu.scss` and `modules/apps/blogs/blogs-web/src/main/resources/META-INF/resources/blogs/css/main.scss`.

7.2.1 GA2 Module CSS depends on the Clay CSS version located in `modules/node_modules/clay-css`. I'm guessing it gets brought in when we build `frontend-theme-unstyled`.

###### 7.2.1 GA2 Clay CSS Version
https://github.com/liferay/liferay-portal/blob/ded0e9390637985231e962e4ad4cfa4639eabb26/modules/apps/frontend-theme/frontend-theme-unstyled/package.json#L3

From my brief research, it looks like you can get Clay CSS functions, variables, mixins to apply globally by creating a local version of [Clay CSS](https://unpkg.com/browse/clay-css@2.18.1/) with your changes. Then update `frontend-theme-unstyled/package.json` to use that one. Not sure on the order, but you need to rebuild and redeploy.

**Closed by pat270** 2020-05-26 18:20 UTC
Labels: comp: clay-css, type: question
