### ISSUE TITLE
DropDown's menu does not align on the first render to the trigger button when a parent DOM element has an absolute or fixed position and also the "right" attribute

### ISSUE THREAD

**Issue by gabrielpramos** [liferay/clay#3588] opened 2020-08-06 17:39 UTC
-   [X] I have searched the [issues](https://github.com/liferay/clay/issues) of this repository and believe that this is not a duplicate.

## Is there an example you can provide via codesandbox.com?
https://codesandbox.io/s/amazing-moore-zvko3?file=/src/index.js

## What are the steps to reproduce?
Click on dropdown trigger button

## What is the expected result?
The menu will not be aligned to the dropdown trigger button

| Tech  | Version |
| ----- | ------- |
| Clay  | @clayui/drop-down: 3.5.0  |
| React |  16.12.0  |

**Comment by gabrielpramos** [comment] 2020-08-06 17:39
cc: @albinojunior

**Comment by gabrielpramos** [comment] 2020-08-06 17:40
a possible fix is removing the right: 0 attribute

**Comment by matuzalemsteles** [comment] 2020-08-06 18:03
Hey @gabrielpramos and @albinojunior, DropDown uses `ReactDOM.createPortal` to render the content, so it will not respect the parent element, because it renders the content in the body or in a nested sub portal, if it is rendered in `<ClayModal/ >`. This is probably related to `domAlign` (https://github.com/liferay/clay/blob/master/packages/clay-drop-down/src/Menu.tsx#L191)

**Comment by matuzalemsteles** [comment] 2022-03-17 23:49
I'm closing this, it's no longer reproducible in the latest version v3.49.0, if it's still reproducible please feel free to open a new issue.

**Closed by matuzalemsteles** 2022-03-17 23:49 UTC
Labels: type: bug, comp: clay-components, 3.x
