### ISSUE TITLE
Clay 2.x: review release process

### ISSUE THREAD

**Issue by julien** [liferay/clay#4576] opened 2022-01-13 11:24 UTC
In the 2.x branch, the [CONTRIBUTING.md](https://github.com/liferay/clay/blob/7b909992f288a54c443004c7b34df8e87172ab1f/CONTRIBUTING.md) file has notes about the [release process](https://github.com/liferay/clay/blob/7b909992f288a54c443004c7b34df8e87172ab1f/CONTRIBUTING.md#release-process).
However, when running `lerna publish from-package` errors are thrown in the console:

```sh
$ lerna publish from-package
ERR! lerna bump must be an explicit version string _or_ one of: 'major', 'minor', 'patch', 'premajor', 'preminor', 'prepatch', 'prerelease', or 'from-git'.
```

If you try to use `lerna publish from-git`, this will happen:

```sh
clay$ lerna publish from-git
lerna notice cli v3.4.3
lerna info Verifying npm credentials
lerna http fetch GET 200 https://registry.npmjs.org/-/whoami 616ms

# Lots of output

[2/4] Logging in...
[3/4] Publishing...
info Two factor authentication enabled.
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.

# More output

error Couldn't publish package: "Can't answer a question unless a user TTY"
``` 

So the only solution left it to publish manually, but once you do that, there are still lots of changes in the repository, and there's no information on what should be done in this case.

Since we need to maintain this branch, we **need** to document this and make sure it works.

**Comment by matuzalemsteles** [comment] 2022-01-25 00:05
I had the same problem recently, not sure why this is causing this error now, I remember we had the same problem in the past but I don't remember how we fixed it, @bryceosterhaus do you remember anything? I remember you had a similar problem.

Maybe it's the global version of lerna we're using, I did a little research on this error but it doesn't say much 🤷‍♂️.

**Comment by bryceosterhaus** [comment] 2022-01-25 03:16
@matuzalemsteles I don't remember what the solution was but I also remember running into this issue. I feel like I just attempted multiple times after cleaning and re-building the repo...

From a cursory google search, it may have to do with being [logged into npm via yarn?](https://github.com/lerna/lerna/issues/1200#issuecomment-364428958)

**Comment by julien** [comment] 2022-01-25 09:47
I'll have a look at this again, I just wanted to point out that once we know what the issue is we should just document it.

**Comment by matuzalemsteles** [comment] 2022-01-25 19:33
Yeah, I agree, publishing 2.x manually is not good, I did this once, and doing it with OTP makes everything even slower 🥲.

> From a cursory google search, it may have to do with being logged into npm via yarn?

Hmm, this is interesting, I found some issues like https://github.com/lerna/lerna/issues/2315 but it seems unrelated, it seems that this error can be caused by different use cases.

**Comment by julien** [comment] 2022-01-26 07:52
I'm wondering if we could find an alternative to lerna: i'm thinking shell script or Makefile (just thinking out loud).

**Comment by matuzalemsteles** [comment] 2022-01-26 16:39
Yes, I think it would be an option, I think we managed to handle the script well to execute the command, like build, but I don't know how I would handle the publishing of several packages to ask for just one OTP.

**Comment by julien** [comment] 2022-01-27 07:55
@matuzalemsteles concerning OTP I have no idea either - that said, we can create a "spike" related to this issue (I think the OTP part will be handled by "yarn" or "npm" itself but I have to verify)

**Comment by matuzalemsteles** [comment] 2022-01-27 16:14
@julien good, we can test this.

**Comment by matuzalemsteles** [comment] 2022-05-05 20:44
I'm going ahead and closing this issue, the original problem was fixed after we updated the Lerna version to v2 and also added CI to v2 to avoid merging things that are breaking. I don't think it's worth it now to try to remove Lerna or rewrite a script for v2, I think just keep publishing is enough for us.

**Closed by matuzalemsteles** 2022-05-05 20:44 UTC
Labels: type: bug, 2.x
