### ISSUE TITLE
Charts design?

### ISSUE THREAD

**Issue by bryceosterhaus** [liferay/clay#459] opened 2018-01-25 00:11 UTC
Hey, I was wondering what the goal for charts is. Are we expecting that clay-charts will match lexicon design? For example, I am looking at the pie chart at https://lexicondesign.io/docs/patterns/Charts/charts.html and noticed that the legend has the actual percentage value for the label. Is that something that will be available out of the box for charts? Also, for bar charts, will it work out of the box to have multiple bars and labels with different colors? 

These are the designs I am hoping for that would work out of the box for charts.
<img width="340" alt="screen shot 2018-01-24 at 4 10 54 pm" src="https://user-images.githubusercontent.com/6843530/35363881-316bac32-0121-11e8-8913-cc5829f3c088.png">
<img width="377" alt="screen shot 2018-01-24 at 4 10 44 pm" src="https://user-images.githubusercontent.com/6843530/35363885-35219b34-0121-11e8-9a73-cb11afd72447.png">

**Comment by bryceosterhaus** [comment] 2018-01-25 00:15
cc @jbalsas

**Comment by jbalsas** [comment] 2018-01-25 00:15
Hey @bryceosterhaus, it is definitely the goal of charts to match Lexicon design out of the box with minimal effort. We'll double-check with the Lexicon team and work on these changes based on their feedback.

Could you share some kind of simple snippet of how you're using it? Just to make sure we reproduce the right thing?

Thanks for letting us know!

**Comment by bryceosterhaus** [comment] 2018-01-25 00:20
We aren't doing anything special. We are just using it as is in JSX.

Very similar to
https://hosting-metalcharts.wedeploy.io/avdanced-examples/x-axis-tick-formatting/
and 
https://hosting-metalcharts.wedeploy.io/simple-examples/pie/

**Comment by julien** [comment] 2018-01-30 08:46
Hi @bryceosterhaus,

Concerning the labels, you could use the chart's [`legend`](https://github.com/liferay/clay/blob/master/packages/clay-charts/src/ChartBase.js#L896-L911) option, which will let you set the position's position.

We need to add the missing (`contents`) property to support legend templates like in this example: https://naver.github.io/billboard.js/demo/#Legend.LegendTemplate2, which would let us customize the labels formatting.

Concerning the chart designs, we might need to review them with the UX team since legends usually contain rectangles instead of circles, but thinking of a solution, we could also solve it by providing custom templates if is a good option.

**Comment by julien** [comment] 2018-01-30 10:18
Hey again @bryceosterhaus,

I added the missing `contents` property to the `legend` [option](https://github.com/julien/clay/blob/5a39f971c5cf104ba4255274528f34a034062bf0/packages/clay-charts/src/ChartBase.js#L897-L900).

It seems we might need to contribute to billboard.js, so that the "data" gets passed to the `template` function, because for the moment it only receives `color` and `title` as arguments.

**Comment by julien** [comment] 2018-01-31 08:18
@bryceosterhaus, I agree and understand your concerns.
This "API" is from billboard.js, so I guess we can to talk with them if we want to modify the current behaviour, or think of another solution. /cc @Robert-Frampton, do you have any thoughts on this?

**Comment by thektan** [comment] 2018-02-13 22:14
Hi @julien! Just checking in to see if any additional progress has been made on this issue.

**Comment by julien** [comment] 2018-02-14 08:08
Hi @thektan,

No additional progress has been made on this issue.

If we want to match the design as it is seen in the screenshots we can do it with the legend option. 
If you have more doubts, I'll be glad to help.

**Comment by jbalsas** [comment] 2018-02-19 10:15
Hey @victorvalle, @emilianocicero, could we get a final say on this design and what's the proper look of these charts?

The main differences from the current implementation are:
- Gap in pie sections
- Legend shapes and values
- Columns colours (being just one series, should all columns have the same colour, or should we allow different colours for the same set?)

Thanks!

**Comment by julien** [comment] 2018-02-19 15:05
After talking with  @victorvalle and @EmilianoCicero,

We will: 

- Provide the template for the pie chart
- Work on the pie chart "gap" to match Lexicon's design
- The bar chart example will be updated in related InVision documents

If you have any doubts or feedback, please let us know.
Thanks!

**Comment by victorvalle** [comment] 2018-02-19 15:55
Related to:

- Legend shapes: the shape of each item the legend has not really the priority. Please do not spend time on that now.
- Legend values: sometimes the legend could incorporate the value if it is easier to read. The designer must have the final decision on whether to use it or not.
- Gap: We agreed with Julien that the should stay as the design marks.
- Bar chart: it will be updated. The different colors or color scale is only for groups, same color where they are not grouped.

**Comment by jbalsas** [comment] 2020-01-20 16:18
Doing some spring-cleaning... closing all issues labeled as 2.x that are not type:bug since 2.x is in maintenance and we won't be proactively be taking these ones.

In this case we're in fact already working on https://github.com/liferay/clay/milestone/14, so no need to keep on this, but a good reminder of the conversation @bryceosterhaus!

Thanks!

**Closed by jbalsas** 2020-01-20 16:18 UTC
Labels: comp: clay-charts, type: question
