### ISSUE TITLE
Claycss.com charts errors

### ISSUE THREAD

**Issue by carloslancha** [liferay/clay#638] opened 2018-02-26 08:53 UTC
While `render:html` task electric is throwing the following errors:
```
Warning: Error: Invalid state passed to 'regions'. Expected type 'object', but received type 'array'. Passed to 'Chart'.
Warning: Error: Invalid state passed to 'axisX.tick.format'. Expected type 'function', but received type 'string'. Passed to 'Chart'.
```

Could you take a look @julien ? Thx!

**Comment by julien** [comment] 2018-02-26 11:05
@carloslancha sure

**Comment by julien** [comment] 2018-02-26 16:33
@carloslancha the first error

```javascript
Warning: Error: Invalid state passed to 'regions'. Expected type 'object', but received type 'array'. Passed to 'Chart'.
```

is fixed in this PR https://github.com/liferay/clay/pull/645.

Concerning the second one
```
Warning: Error: Invalid state passed to 'axisX.tick.format'. Expected type 'function', but received type 'string'. Passed to 'Chart'.
```
I'm still not sure how to fix it. In this case we would need to create a `<script>` tag in the `.md` file and pass it to the `.soy` template call. 
@zenorocha Do you think this would be possible?

**Comment by julien** [comment] 2018-03-15 12:05
Hi @zenorocha, have you had a chance to think about this?

**Comment by zenorocha** [comment] 2018-03-15 17:15
Sorry guys, I wasn't able to take a look on this, I suggest putting someone else to evaluate it

**Comment by matuzalemsteles** [comment] 2018-09-04 18:14
hey guys, this is no longer reproduced since we're with Gatsby. I'm closing it.

**Closed** 2018-09-04 18:14 UTC
Labels: bug
